config/routes.rb
Rails.application.routes.draw do
  root 'page#home'

  get '/ohoac/administration/adminsessions/login', to: 'admin_sessions#new'
  post '/ohoac/administration/adminsessions/login', to: 'admin_sessions#create'
  delete '/ohoac/administration/adminsessions/logout', to: 'admin_sessions#destroy'

  get '/ohoac/administration/signup', to: 'admins#new'
  post '/ohoac/administration/signup', to: 'admins#create'

  get '/ohoac/administration/dashboard', to: 'admins#dashboard'

  get '/ohoac/administration/dashboard/users/all', to: 'admins#users'
  get '/ohoac/administration/dashboard/users/:user_id/user_appointments', to: 'admins#user_appointments', as: '/ohoac/administration/users/appointments'
  get '/ohoac/administration/dashboard/doctors/all', to: 'admins#doctors'
  get '/ohoac/administration/dashboard/messages_board/mails/all', to: 'admins#contacts'
  get '/ohoac/administration/dashboard/messages_board/mails/all/selected/read/:id', to: 'admins#read', as: '/ohoac/administration/dashboard/messages_board/mails/all/selected/read/'
  delete '/ohoac/administration/dashboard/messages_board/mails/all/contacts/:contact_id', to: 'admins#destroy_message', as: '/ohoac/administration/dashboard/messages_board/mails/all/remove'
  get '/ohoac/administration/dashboard/doctor/new', to: 'admins#new_doctor'
  post '/ohoac/administration/dashboard/doctor/new', to: 'admins#create_doctor'
  post '/ohoac/administration/dashboard/department/new', to: 'admins#create_department', as: '/ohoac/administration/dashboard/department/add_new'

  delete '/ohoac/administration/dashboard/department/selected/remove/:department_id', to: 'admins#remove_department', as: '/ohoac/administration/dashboard/department/selected/remove_department'


  get '/about', to: 'page#about'
  get '/terms', to: 'page#terms'
  get '/faqs', to: 'page#faqs'

   get '/contact_us', to: 'contacts#new'
   post '/contact_us', to: 'contacts#create'


  #user has the ability to sign up an account
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  #uri for user session
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  #uri for doctors session to sign in only
  get '/signin', to: 'doctor_sessions#new'
  post '/signin', to: 'doctor_sessions#create'
  delete '/signout', to: 'doctor_sessions#destroy'

  get '/refresh_appointments', to: 'doctors#refresh_appointments'


  #appointment
  get '/users/:user_id/doctors/:doctor_id/appointments/new',
      to: "appointments#new", as: 'schedule_appointment'

  resources :users, except: [:new, :create, :index] do
    resources :doctors, except: [:index, :create, :edit, :new, :show, :update, :destroy] do
      resources :appointments, except: [:new, :index]

    end

  end
  resources :doctors, except: [:index]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admins/appointments.html.erb
<%provide(:title, "#{@user.first_name} Appointments - O-HoAC") %>
<div class="row row-top">
	<h2 style="text-align: center">
		All <%= "#{@user.first_name.upcase} #{@user.last_name.upcase}" %>  Appointments
	</h2>
		<hr>
		<div class="row">
			<div class="large-6 columns">
				<ul class="menu">
  					<li><%= link_to "DASHBOARD", ohoac_administration_dashboard_path %></li>
  					<li><%= link_to "ALL DOCTORS", ohoac_administration_dashboard_doctors_all_path %></li>
  					<li><%= link_to "ALL USERS", ohoac_administration_dashboard_users_all_path %></li>	
				</ul>			
			</div>
		</div>
	<div class="large-12 columns" style="margin-bottom: 50px">
		<h3 style="text-align: center">list of <%= "#{@user.first_name.downcase} #{@user.last_name}"%> appointments</h3>
		<% if !@appointments.empty? %>
		<table>
		<tr>
			<th>Appointment Reason</th>
			<th>Appointment Date</th>
			<th>Doctor's Name</th>
			<th>Department</th>
		</tr>
<% @appointments.each do |appointment| %>
		<tr>
			<div class="row">
				<div class="large-12 columns">
				<td><%= appointment.reason %></td>
				<td><%= appointment.apt_date.strftime("%B %d, %Y") %></td>
				<td><%= appointment.doctor.doctors_name.capitalize %></td>
				<td><%= appointment.doctor.department.department_name%></td>
				</div>
			</div>
			
				
			
		</tr>
	<%end%>
		
		</table>
		<%else%>
		<p>Nothing in here</p>
		<%end%>
	</div>

</div>

app/views/admins/contacts.html.erb
<%provide(:title, "All Inbox Mails - O-HoAC") %>
<div class="row row-top">
	<h2 style="text-align: center">
		Messages Board
	</h2>
		<hr>
		<div class="row">
			<div class="large-6 columns">
				<ul class="menu">
  					<li><%= link_to "DASHBOARD", ohoac_administration_dashboard_path %></li>
  					<li><%= link_to "ALL DOCTORS", ohoac_administration_dashboard_doctors_all_path %></li>
  					<li><%= link_to "ALL USERS", ohoac_administration_dashboard_users_all_path %></li>	
				</ul>			
			</div>
		</div>
	<div class="large-12 columns" style="margin-bottom: 50px">
		<h3 style="text-align: center">list of mails</h3>
		
		<table>
		<tr>
			<th>Full Names</th>
			<th>Email Address</th>
			<th>Mobile Number</th>
			<th>Message</th>
		</tr>
<% @contacts.each do |contact| %>
		<tr id="contact_id_<%= contact.id %>">
			<div class="row">
				<div class="large-12 columns">
				<td><%= contact.full_name %></td>
				<td><%= contact.email %></td>
				<td><%= contact.mobile %></td>
				<% if contact.read_message %>
				<td><span style="color: #000000"> <%= link_to 'Old', ohoac_administration_dashboard_messages_board_mails_all_selected_read_path(contact.id)%></span> <span> | </span><a data-open="mail_<%="#{contact.id}"%>" style="color: #000000;">unread</a><span> | </span><%= link_to 'delete', ohoac_administration_dashboard_messages_board_mails_all_remove_path(contact.id), method: :delete, data: { confirm: 'Are you sure? '}, remote: true, style: "color: red;"%></td>
				 <%else%>
				 <td>
				 	<%= link_to 'Recent', ohoac_administration_dashboard_messages_board_mails_all_selected_read_path(contact.id),
				 id: "mail_#{contact.id}"%><span> | </span><%= link_to 'unread'%><span> | </span><%= link_to 'delete', ohoac_administration_dashboard_messages_board_mails_all_remove_path(contact.id), method: :delete, data: { confirm: 'Are you sure? '}, remote: true%>
				 </td>
				 <%end%>
				</div>
			</div>
			
				<div class="reveal" id="mail_<%="#{contact.id}"%>" data-reveal>
  				<h3>
  					<strong><%= contact.message_title %></strong>
  					<hr>
  				</h3>
  				<p class="lead"><%= contact.message %></p>
  				<button class="close-button" data-close aria-label="Close modal" type="button">
    				<span aria-hidden="true">&times;</span>
  				</button>
		</div>
			
		</tr>
		
	<%end%>
		
		</table>
		
	</div>

</div>

app/views/admins/dashboard.html.erb
<%provide(:title, "Adminstrative Dashboard - O-HoAC") %>
<div class="row row-top">
<h2 style="text-align: center">
	Welcome to adminstrative dashboard
</h2>
<hr>
	<div class="large-6 columns">
		<div class="card">

                <div class="image">
                <h1 style="text-align: center">
                 	<%= link_to pluralize(@users.count, 'Patient'),  ohoac_administration_dashboard_users_all_path%>
                </h1>
                </div>


                <div class="action">
                <p>- Features -</p>
                <ul>
                  <li>How many appointments each patient as made</li>
                  <li>When was the appointment made</li>
                  <li>To which doctor was the appointment made to</li>
                  <li>To which hospital is that doctor</li>
                </ul>
               
                </div>
               
              </div>
	</div>
	<div class="large-6 columns">
			
		<div class="card">

                <div class="image">
               		<h1 style="text-align: center">
                 	<%= link_to pluralize(@doctors.count, 'Doctor'), ohoac_administration_dashboard_doctors_all_path%>
                </h1>
                </div>


                <div class="action">

                  <!--<a></a>-->
                  <p>
                  	- Features -
                  </p>
                  <ul>
                    <li>How many appointment each doctor has received</li>
                    <li>Who made the appointment</li>
                    <li>At what date and time was the appointment made</li>
                    <li>In which hospital is the doctor</li>
                  </ul>
                 
                  <%= link_to "New Doctor", ohoac_administration_dashboard_doctor_new_path %>
                  <a data-open="form">Add Department</a>
                  <div class="reveal" id="form" data-reveal>
                        <h1>Add new department</h1>
                          <div class="row">
                          <div class="large-5 columns">
                            <% @departments.each do |department| %>
                              <a id="<%=department.id %>"><%=department.department_name %></a> <span> | </span><%= link_to 'remove',ohoac_administration_dashboard_department_selected_remove_department_path(department.id), method: :delete, data: { confirm: 'Are you sure?'} %><br>
                            <%end%>
                          </div>
                            <div class="large-7 columns">
                              <%= form_for(@department, url: ohoac_administration_dashboard_department_add_new_path) do |f| %>
                                <%= render "users/shared/error_messages", object: @department %>
                                <%= f.label :department_name %>
                                <%= f.text_field :department_name, placeholder: 'enter department name here' %>
                                <%= f.submit 'add', class: 'button large-5' %>
                              <%end%>
                            </div>
                          </div>
                        <button class="close-button" data-close aria-label="Close modal" type="button">
                         <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                  <a>Add City </a>

                </div>
                


        </div>
	</div>
</div>

<div class="row">
  <div class="large-6 columns">
  
    <div class="card">

                <div class="image">
                  <h1 style="text-align: center">
                  <%= link_to pluralize(@contacts.count, 'Mail'), ohoac_administration_dashboard_messages_board_mails_all_path%>
                </h1>
                </div>


                <div class="action">

                 
                  <p>
                    - Features -
                  </p>
                  <ul>
                    <li>Who asked what</li>
                    <li>People by name who asked what</li>
                    <li>Do they want to belong</li>
                  </ul>
                

                </div>
                


        </div>
  </div>
  
</div>

app/views/admins/destroy_message.js.erb
$('#contact_id_<%= @message.id %>').remove();

app/views/admins/doctors.html.erb
<%provide(:title, "All Doctors - O-HoAC") %>
<div class="row row-top">
	<h2 style="text-align: center">
		All O-HoAC Doctors
	</h2>
	<hr>
<div class="row">
	<div class="large-5 columns">

		<ul class="menu">
  			<li><%= link_to "DASHBOARD", ohoac_administration_dashboard_path %></li>
  			<li><%= link_to "ALL PATIENTS", ohoac_administration_dashboard_users_all_path %></li>
  			<li><%= link_to "ALL MAILS", ohoac_administration_dashboard_messages_board_mails_all_path %></li>

		</ul>			
	</div>
</div>
	<div class="large-12 columns" style="margin-bottom: 50px">
		<h3 style="text-align: center">list of doctors</h3>
		<% if !@doctors.empty? %>
		<table>
		<tr>
			<th>Full Names</th>
			<th>Profile Names</th>
			<th>Current Hospital</th>
			<th>Mobile Contact</th>
			<th>No. Of Appointments</th>
		</tr>
      <% @doctors.each do |doctor| %>
		<tr>

				<td><%= link_to "#{doctor.first_name} #{doctor.last_name}"%></td>
				<td><%= doctor.doctors_name %></td>
				<td><%= doctor.current_hospital %></td>
				<td><%= doctor.phone_number %></td>
				<td><%= link_to "#{doctor.appointments.count}"%></td>

		</tr>
      <%end%>
		
		</table>
		<%else%>
		<p>not here</p>
		<%end%>
	</div>

</div>

app/views/admins/new.html.erb
<%provide(:title, 'Administrative sign up - O-HoAC') %>
<div class="row row-top">
<h2 style="text-align: center">Administrative Sign up Section</h2>
<hr>
	<div class="large-5 columns">
	<p>
		Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	</p>
	</div>
	<div class="large-7 columns">
		<h2>Administrative Login form</h2>
		<%= render 'admins/shared/form' %>
	</div>

</div>

app/views/admins/new_doctor.html.erb
<%provide(:title, 'New Doctors Account - Administrator')%>
<div class="row row-top">
<div class="large-4 columns">
	<h4>O-HoAC</h4>
	<hr>
	<p>
		Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	</p>
</div>
 <div class="large-4 columns">
 	<h3>Add doctor</h3>
 	<%= render 'admins/shared/new_doc' %>
 </div>
</div>

app/views/admins/read.html.erb
<%provide(:title, "Read mail - O-HoAC") %>
<div class="row row-top">
	<h2 style="text-align: center">
		Read inbox mail
	</h2>
		<hr>
		<div class="row">
			<div class="large-6 columns">
				<ul class="menu">
  					<li><%= link_to "DASHBOARD", ohoac_administration_dashboard_path %></li>
  					<li><%= link_to "ALL DOCTORS", ohoac_administration_dashboard_doctors_all_path %></li>
  					<li><%= link_to "ALL USERS", ohoac_administration_dashboard_users_all_path %></li>	
  					<li><%= link_to "ALL MAILS", ohoac_administration_dashboard_messages_board_mails_all_path %></li>	
				</ul>			
			</div>
		</div>
	<div class="large-12 columns" style="margin-bottom: 50px">
		<h3 style="text-align: center">list of mails > mail id <%= @selected.id %></h3>
		<hr>

		<div style="background-color: #ffffff; padding: 10px;">
			<strong>From: </strong><a><%= @selected.email %></a><br>
			<strong>Subject:</strong><br>
			<h4><%= @selected.message_title %></h4>
			<div class="row">
			<div class="large-4 columns">
			<strong>Message:</strong><br>
			<p>
			<%= @selected.message %>
			</p>
			</div>
			</div>
		</div>

	</div>
</div>

app/views/admins/user_appointments.html.erb
<%provide(:title, "#{@user.first_name} Appointments - O-HoAC") %>
<div class="row row-top">
	<h2 style="text-align: center">
		All <%= "#{@user.first_name.upcase} #{@user.last_name.upcase}" %>  Appointments
	</h2>
		<hr>
		<div class="row">
			<div class="large-6 columns">
				<ul class="menu">
  					<li><%= link_to "DASHBOARD", ohoac_administration_dashboard_path %></li>
  					<li><%= link_to "ALL DOCTORS", ohoac_administration_dashboard_doctors_all_path %></li>
  					<li><%= link_to "ALL USERS", ohoac_administration_dashboard_users_all_path %></li>	
  					<li><%= link_to "ALL MAILS", ohoac_administration_dashboard_messages_board_mails_all_path %></li>	
				</ul>			
			</div>
		</div>
	<div class="large-12 columns" style="margin-bottom: 50px">
		<h3 style="text-align: center">list of <%= "#{@user.first_name.downcase} #{@user.last_name}"%> appointments</h3>
		<% if !@user_appointments.empty? %>
		<table>
		<tr>
			<th>Appointment Reason</th>
			<th>Appointment Date</th>
			<th>Doctor's Name</th>
			<th>Department</th>
		</tr>
<% @user_appointments.each do |appointment| %>
		<tr>
			<div class="row">
				<div class="large-12 columns">
				<td><%= appointment.reason %></td>
				<td><%= appointment.apt_date.strftime("%B %d, %Y") %></td>
				<td><%= appointment.doctor.doctors_name.capitalize %></td>
				<td><%= appointment.doctor.department.department_name%></td>
				</div>
			</div>
			
				
			
		</tr>
	<%end%>
		
		</table>
		<%else%>
		<p>Nothing in here</p>
		<%end%>
	</div>

</div>

app/views/admins/users.html.erb
<%provide(:title, "All Patients - O-HoAC") %>
<div class="row row-top">
<h2 style="text-align: center">
	All O-HoAC Patients
</h2>
<hr>
<div class="row">
<div class="large-5 columns">

		<ul class="menu">
  			<li><%= link_to "DASHBOARD", ohoac_administration_dashboard_path%></li>
  			<li><%= link_to "ALL DOCTORS", ohoac_administration_dashboard_doctors_all_path %></li>
  			<li><%= link_to "ALL MAILS", ohoac_administration_dashboard_messages_board_mails_all_path %></li>
		</ul>			
	</div>
</div>
	<div class="large-12 columns" style="margin-bottom: 50px">
		<h3 style="text-align: center">list of patients</h3>
		<% if !@users.empty? %>
		<table>
		<tr>
			<th>Full Names</th>
			<th>Profile Name</th>
			<th>Email Address</th>
			<th>Mobile Contact</th>
			<th>No. Of Appointments</th>
		</tr>
	<% @users.each do |user| %>
		<tr>
			
				<td><%= link_to "#{user.first_name} #{user.last_name}"%></td>
				<td><%= user.name %></td>
				<td><%= user.email %></td>
				<td><%= user.mobile_phone %></td>
				<td><%= link_to "#{user.appointments.count}", ohoac_administration_users_appointments_path(user) %></td>
			
		</tr>
	<%end%>
		
		</table>
		<%else%>
		<p>not here</p>
		<%end%>
	</div>
</div>